### ISSUE TITLE
RichText::convert() undefined

### ISSUE THREAD

**Issue by luke-** [humhub/meeting-issues#24]
Probably connected with: https://github.com/humhub/humhub-modules-meetings/issues/10

Should we have increased the Min version here?

```
Error: Call to undefined method humhub\modules\content\widgets\richtext\RichText::convert() in /hidden/humhub/protected/modules/meeting/views/index/print.php:55 
Stack trace: #0 /hidden/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require() 
#1 /hidden/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/kunden/503984_...', Array) 
#2 /hidden/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/kunden/503984_...', Array, Object(humhub\modules\meeting\controllers\IndexController)) 
#3 /hidden/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(441): yii\base\View->render('print', Array, Object(humhub\modules\meeting\controllers\IndexController)) 
#4 /hidden/humhub/protected/modules/meeting/controllers/IndexController.php(147): yii\base\Controller->renderPartial('print', Array) 
#5 [internal function]: humhub\modules\meeting\controllers\IndexController->actionPrint('625') #6 /hidden/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) 
#7 /hidden/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) 
#8 /hidden/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('print', Array) 
#9 /hidden/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('meeting/index/p...', Array) 
#10 /hidden/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request)) 
#11 /hidden/humhub/index.php(25): yii\base\Application->run() #12 {main}
```

**Comment by luke-** [comment]
Caused when using the "Print Agenda" option

**Comment by buddh4** [comment]
Yes `RichText::convert()` ist only available in 1.8

**Comment by yurabakhtin** [comment]
@luke- Sorry, I need to be more careful when use new functions.
Fixed in MR https://git.humhub.org/modules/meeting/-/merge_requests/4

**Comment by luke-** [comment]
Thanks!
