### ISSUE TITLE
Unable to delete Agenda Items

### ISSUE THREAD

**Issue by luke-** [humhub/meeting-issues#33]
HumHub Version 14.2

**Comment by luke-** [comment]
```
elete meeting_task 144 without existing task relation! (yes|no) [no]:y
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: humhub\modules\meeting\models\MeetingTask::hardDelete()'

in /srv/var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /srv/var/www/humhub/protected/modules/meeting/Events.php(77): yii\base\Component->__call()
#1 [internal function]: humhub\modules\meeting\Events::onIntegrityCheck()
#2 /srv/var/www/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#3 /srv/var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#4 /srv/var/www/humhub/protected/humhub/commands/IntegrityController.php(39): yii\base\Component->trigger()
#5 [internal function]: humhub\commands\IntegrityController->actionRun()
#6 /srv/var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /srv/var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#8 /srv/var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#9 /srv/var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#10 /srv/var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#11 /srv/var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#12 /srv/var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#13 /srv/var/www/humhub/protected/yii(29): yii\base\Application->run()
#14 {main}


```

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/meeting/pull/29.

**Comment by luke-** [comment]
@yurabakhtin Thanks. Can you please prepare a new release?

**Comment by yurabakhtin** [comment]
@luke- Done https://github.com/humhub/meeting/releases/tag/v0.7.1

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by luke-** [comment]
@yurabakhtin Can you please check again. The issue is about 2 bugs. One in integrity check and a problem regarding deleteion of agenda item.

"The agenda entry remains even though it reloads the view."

**Comment by yurabakhtin** [comment]
> a problem regarding deleteion of agenda item.
> 
> "The agenda entry remains even though it reloads the view."

@luke- Fixed in PR https://github.com/humhub/meeting/pull/30.

**Comment by luke-** [comment]
@yurabakhtin Thanks, can you please release the new version.

**Comment by yurabakhtin** [comment]
@luke- Done https://github.com/humhub/meeting/releases/tag/v0.7.2
